// src/views/ActuatorManager.vue
<template>
  <div>
    <v-row>
      <v-col cols="12">
        <v-card>
          <v-card-title>
            <v-icon class="mr-2">mdi-cog</v-icon>
            Actuator Management
          </v-card-title>
          <v-card-text>
            <v-alert type="warning" class="mb-4">
              <strong>⚠️ Safety Warning</strong>
              Incorrect configuration can permanently damage your actuator. Always backup memory before making changes.
            </v-alert>
          </v-card-text>
        </v-card>
      </v-col>
    </v-row>

    <v-row class="mt-4">
      <v-col cols="12" md="6">
        <v-card>
          <v-card-title>CAN Interface Setup</v-card-title>
          <v-card-text>
            <v-select
              v-model="selectedInterface"
              :items="canInterfaces"
              label="CAN Interface"
              prepend-icon="mdi-network"
              hint="Select your CAN interface (socketcan, slcan, etc.)"
              persistent-hint
            />
            
            <v-text-field
              v-model="channel"
              label="Channel"
              prepend-icon="mdi-cable-data"
              hint="e.g., can0, /dev/ttyUSB0"
              persistent-hint
              class="mt-4"
            />

            <v-btn
              :color="connectionStatus === 'connected' ? 'success' : 'primary'"
              :loading="connecting"
              @click="toggleConnection"
              block
              class="mt-4"
            >
              <v-icon start>{{ connectionStatus === 'connected' ? 'mdi-lan-disconnect' : 'mdi-lan-connect' }}</v-icon>
              {{ connectionStatus === 'connected' ? 'Disconnect' : 'Connect' }}
            </v-btn>

            <v-chip
              :color="connectionStatus === 'connected' ? 'success' : 'error'"
              class="mt-2"
            >
              {{ connectionStatus }}
            </v-chip>
          </v-card-text>
        </v-card>
      </v-col>

      <v-col cols="12" md="6">
        <v-card>
          <v-card-title>Actuator Information</v-card-title>
          <v-card-text>
            <v-list>
              <v-list-item>
                <v-list-item-title>Type</v-list-item-title>
                <v-list-item-subtitle>{{ actuatorInfo.type || 'Unknown' }}</v-list-item-subtitle>
              </v-list-item>
              <v-list-item>
                <v-list-item-title>Current Position</v-list-item-title>
                <v-list-item-subtitle>{{ actuatorInfo.currentPosition || 'N/A' }}</v-list-item-subtitle>
              </v-list-item>
              <v-list-item>
                <v-list-item-title>Min Position</v-list-item-title>
                <v-list-item-subtitle>{{ actuatorInfo.minPosition || 'N/A' }}</v-list-item-subtitle>
              </v-list-item>
              <v-list-item>
                <v-list-item-title>Max Position</v-list-item-title>
                <v-list-item-subtitle>{{ actuatorInfo.maxPosition || 'N/A' }}</v-list-item-subtitle>
              </v-list-item>
            </v-list>

            <v-btn
              :disabled="connectionStatus !== 'connected'"
              @click="readActuatorInfo"
              variant="outlined"
              class="mt-4"
            >
              <v-icon start>mdi-refresh</v-icon>
              Refresh Info
            </v-btn>
          </v-card-text>
        </v-card>
      </v-col>
    </v-row>

    <v-row class="mt-4">
      <v-col cols="12">
        <v-card>
          <v-card-title>Position Configuration</v-card-title>
          <v-card-text>
            <v-row>
              <v-col cols="12" md="4">
                <v-text-field
                  v-model="newMinPosition"
                  label="New Min Position (hex)"
                  prepend-icon="mdi-arrow-down-bold"
                  placeholder="0x0113"
                  :disabled="connectionStatus !== 'connected'"
                />
              </v-col>
              <v-col cols="12" md="4">
                <v-text-field
                  v-model="newMaxPosition"
                  label="New Max Position (hex)"
                  prepend-icon="mdi-arrow-up-bold"
                  placeholder="0x0220"
                  :disabled="connectionStatus !== 'connected'"
                />
              </v-col>
              <v-col cols="12" md="4" class="d-flex align-center">
                <v-btn
                  :disabled="connectionStatus !== 'connected' || !newMinPosition || !newMaxPosition"
                  @click="updatePositions"
                  color="warning"
                  block
                >
                  <v-icon start>mdi-update</v-icon>
                  Update Positions
                </v-btn>
              </v-col>
            </v-row>

            <v-divider class="my-4" />

            <v-btn
              :disabled="connectionStatus !== 'connected'"
              @click="autoCalibrate"
              color="primary"
              class="mr-4"
            >
              <v-icon start>mdi-auto-fix</v-icon>
              Auto Calibrate
            </v-btn>

            <v-btn
              :disabled="connectionStatus !== 'connected'"
              @click="readMemory"
              color="info"
            >
              <v-icon start>mdi-download</v-icon>
              Read Memory
            </v-btn>
          </v-card-text>
        </v-card>
      </v-col>
    </v-row>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';

// Interface options
const canInterfaces = ['socketcan', 'slcan', 'virtual'];
const selectedInterface = ref('socketcan');
const channel = ref('can0');

// Connection state
const connectionStatus = ref<'disconnected' | 'connecting' | 'connected'>('disconnected');
const connecting = ref(false);

// Actuator information
const actuatorInfo = ref({
  type: '',
  currentPosition: '',
  minPosition: '',
  maxPosition: '',
});

// Position configuration
const newMinPosition = ref('');
const newMaxPosition = ref('');

// Methods
const toggleConnection = async () => {
  if (connectionStatus.value === 'connected') {
    // Disconnect
    connectionStatus.value = 'disconnected';
    return;
  }

  // Connect
  connecting.value = true;
  connectionStatus.value = 'connecting';
  
  try {
    // TODO: Implement actual CAN connection
    await new Promise(resolve => setTimeout(resolve, 2000)); // Simulate connection
    connectionStatus.value = 'connected';
  } catch (error) {
    connectionStatus.value = 'disconnected';
    console.error('Connection failed:', error);
  } finally {
    connecting.value = false;
  }
};

const readActuatorInfo = async () => {
  try {
    // TODO: Implement actual actuator reading
    actuatorInfo.value = {
      type: 'Hella Universal Turbo Actuator I',
      currentPosition: '0x0180',
      minPosition: '0x0113',
      maxPosition: '0x0220',
    };
  } catch (error) {
    console.error('Failed to read actuator info:', error);
  }
};

const updatePositions = async () => {
  try {
    // TODO: Implement position updates
    console.log('Updating positions:', { min: newMinPosition.value, max: newMaxPosition.value });
  } catch (error) {
    console.error('Failed to update positions:', error);
  }
};

const autoCalibrate = async () => {
  try {
    // TODO: Implement auto calibration
    console.log('Starting auto calibration...');
  } catch (error) {
    console.error('Auto calibration failed:', error);
  }
};

const readMemory = async () => {
  try {
    // TODO: Implement memory reading
    console.log('Reading memory...');
  } catch (error) {
    console.error('Memory read failed:', error);
  }
};
</script>

// src/components/ActuatorManager.tsx
import React, { useState } from 'react';
import {
  Typography,
  Paper,
  Box,
  Alert,
  Grid,
  TextField,
  Button,
  Select,
  MenuItem,
  FormControl,
  InputLabel,
  Chip,
  List,
  ListItem,
  ListItemText,
  Divider,
} from '@mui/material';
import { Wifi, WifiOff, Refresh, Update, AutoFixHigh, Download } from '@mui/icons-material';

function ActuatorManager() {
  const [selectedInterface, setSelectedInterface] = useState('socketcan');
  const [channel, setChannel] = useState('can0');
  const [connectionStatus, setConnectionStatus] = useState<'disconnected' | 'connecting' | 'connected'>('disconnected');
  const [connecting, setConnecting] = useState(false);
  const [newMinPosition, setNewMinPosition] = useState('');
  const [newMaxPosition, setNewMaxPosition] = useState('');

  const actuatorInfo = {
    type: 'Hella Universal Turbo Actuator I',
    currentPosition: '0x0180',
    minPosition: '0x0113',
    maxPosition: '0x0220',
  };

  const handleConnect = async () => {
    if (connectionStatus === 'connected') {
      setConnectionStatus('disconnected');
      return;
    }

    setConnecting(true);
    setConnectionStatus('connecting');
    
    // Simulate connection
    setTimeout(() => {
      setConnectionStatus('connected');
      setConnecting(false);
    }, 2000);
  };

  return (
    <Box>
      <Typography variant="h4" gutterBottom>
        Actuator Management
      </Typography>

      <Alert severity="warning" sx={{ mb: 3 }}>
        <strong>⚠️ Safety Warning</strong> Incorrect configuration can permanently 
        damage your actuator. Always backup memory before making changes.
      </Alert>

      <Grid container spacing={3}>
        <Grid item xs={12} md={6}>
          <Paper sx={{ p: 3 }}>
            <Typography variant="h6" gutterBottom>
              CAN Interface Setup
            </Typography>
            
            <FormControl fullWidth sx={{ mb: 2 }}>
              <InputLabel>CAN Interface</InputLabel>
              <Select
                value={selectedInterface}
                label="CAN Interface"
                onChange={(e) => setSelectedInterface(e.target.value)}
              >
                <MenuItem value="socketcan">SocketCAN</MenuItem>
                <MenuItem value="slcan">SLCAN</MenuItem>
                <MenuItem value="virtual">Virtual CAN</MenuItem>
              </Select>
            </FormControl>

            <TextField
              fullWidth
              label="Channel"
              value={channel}
              onChange={(e) => setChannel(e.target.value)}
              helperText="e.g., can0, /dev/ttyUSB0"
              sx={{ mb: 3 }}
            />

            <Button
              fullWidth
              variant="contained"
              color={connectionStatus === 'connected' ? 'error' : 'primary'}
              onClick={handleConnect}
              disabled={connecting}
              startIcon={connectionStatus === 'connected' ? <WifiOff /> : <Wifi />}
              sx={{ mb: 2 }}
            >
              {connectionStatus === 'connected' ? 'Disconnect' : 'Connect'}
            </Button>

            <Chip
              label={connectionStatus}
              color={connectionStatus === 'connected' ? 'success' : 'default'}
              variant="outlined"
            />
          </Paper>
        </Grid>

        <Grid item xs={12} md={6}>
          <Paper sx={{ p: 3 }}>
            <Typography variant="h6" gutterBottom>
              Actuator Information
            </Typography>
            
            <List>
              <ListItem>
                <ListItemText 
                  primary="Type" 
                  secondary={actuatorInfo.type} 
                />
              </ListItem>
              <ListItem>
                <ListItemText 
                  primary="Current Position" 
                  secondary={actuatorInfo.currentPosition} 
                />
              </ListItem>
              <ListItem>
                <ListItemText 
                  primary="Min Position" 
                  secondary={actuatorInfo.minPosition} 
                />
              </ListItem>
              <ListItem>
                <ListItemText 
                  primary="Max Position" 
                  secondary={actuatorInfo.maxPosition} 
                />
              </ListItem>
            </List>

            <Button
              variant="outlined"
              startIcon={<Refresh />}
              disabled={connectionStatus !== 'connected'}
              sx={{ mt: 2 }}
            >
              Refresh Info
            </Button>
          </Paper>
        </Grid>

        <Grid item xs={12}>
          <Paper sx={{ p: 3 }}>
            <Typography variant="h6" gutterBottom>
              Position Configuration
            </Typography>
            
            <Grid container spacing={2} sx={{ mb: 3 }}>
              <Grid item xs={12} md={4}>
                <TextField
                  fullWidth
                  label="New Min Position (hex)"
                  value={newMinPosition}
                  onChange={(e) => setNewMinPosition(e.target.value)}
                  placeholder="0x0113"
                  disabled={connectionStatus !== 'connected'}
                />
              </Grid>
              <Grid item xs={12} md={4}>
                <TextField
                  fullWidth
                  label="New Max Position (hex)"
                  value={newMaxPosition}
                  onChange={(e) => setNewMaxPosition(e.target.value)}
                  placeholder="0x0220"
                  disabled={connectionStatus !== 'connected'}
                />
              </Grid>
              <Grid item xs={12} md={4} sx={{ display: 'flex', alignItems: 'center' }}>
                <Button
                  fullWidth
                  variant="contained"
                  color="warning"
                  startIcon={<Update />}
                  disabled={connectionStatus !== 'connected' || !newMinPosition || !newMaxPosition}
                >
                  Update Positions
                </Button>
              </Grid>
            </Grid>

            <Divider sx={{ my: 3 }} />

            <Box sx={{ display: 'flex', gap: 2 }}>
              <Button
                variant="contained"
                startIcon={<AutoFixHigh />}
                disabled={connectionStatus !== 'connected'}
              >
                Auto Calibrate
              </Button>
              <Button
                variant="contained"
                color="info"
                startIcon={<Download />}
                disabled={connectionStatus !== 'connected'}
              >
                Read Memory
              </Button>
            </Box>
          </Paper>
        </Grid>
      </Grid>
    </Box>
  );
}

export default ActuatorManager;
