// src/views/Dashboard.vue
<template>
  <div>
    <v-row>
      <v-col cols="12">
        <v-card>
          <v-card-title>
            <v-icon class="mr-2">mdi-car-turbocharger</v-icon>
            Welcome to Hella Turbo Controller
          </v-card-title>
          <v-card-text>
            <v-alert type="info" class="mb-4">
              <strong>🎉 New TypeScript Version!</strong>
              This is the modern, cross-platform version built with Electron + Vue + Vuetify.
            </v-alert>
            
            <p class="text-h6 mb-3">🔧 What's New:</p>
            <v-list>
              <v-list-item prepend-icon="mdi-check-circle" title="Cross-platform GUI (Windows, Mac, Linux)" />
              <v-list-item prepend-icon="mdi-check-circle" title="TypeScript for better safety and development" />
              <v-list-item prepend-icon="mdi-check-circle" title="Modern Vue 3 + Vuetify Material Design" />
              <v-list-item prepend-icon="mdi-check-circle" title="Enhanced memory visualization" />
              <v-list-item prepend-icon="mdi-check-circle" title="Real-time CAN monitoring" />
            </v-list>

            <v-alert type="warning" class="mt-4">
              <strong>⚠️ Safety First!</strong>
              This tool can permanently damage actuators if used incorrectly. 
              Always backup memory dumps and understand the analysis before making changes.
            </v-alert>
          </v-card-text>
        </v-card>
      </v-col>
    </v-row>

    <v-row class="mt-4">
      <v-col cols="12" md="6">
        <v-card>
          <v-card-title>Quick Start</v-card-title>
          <v-card-text>
            <v-stepper alt-labels>
              <v-stepper-header>
                <v-stepper-item value="1" title="Connect CAN" />
                <v-divider />
                <v-stepper-item value="2" title="Configure Actuator" />
                <v-divider />
                <v-stepper-item value="3" title="Read Memory" />
                <v-divider />
                <v-stepper-item value="4" title="Analyze" />
              </v-stepper-header>
            </v-stepper>
          </v-card-text>
        </v-card>
      </v-col>

      <v-col cols="12" md="6">
        <v-card>
          <v-card-title>Legacy Python Version</v-card-title>
          <v-card-text>
            <p>The original Python CLI tools are available in the <code>legacy-python/</code> folder.</p>
            <v-btn variant="outlined" class="mt-2">
              <v-icon start>mdi-folder</v-icon>
              View Legacy Tools
            </v-btn>
          </v-card-text>
        </v-card>
      </v-col>
    </v-row>
  </div>
</template>

<script setup lang="ts">
// Dashboard component - landing page
</script>

// src/components/Dashboard.tsx
import React from "react";
import {
  Typography,
  Paper,
  Box,
  Alert,
  List,
  ListItem,
  ListItemIcon,
  ListItemText,
  Button,
  Grid,
  Stepper,
  Step,
  StepLabel,
} from "@mui/material";
import { CheckCircle, Folder, Warning } from "@mui/icons-material";

const steps = ["Connect CAN", "Configure Actuator", "Read Memory", "Analyze"];

function Dashboard() {
  return (
    <Box>
      <Typography variant="h4" gutterBottom>
        Welcome to Hella Turbo Controller
      </Typography>

      <Grid container spacing={3}>
        <Grid item xs={12}>
          <Paper sx={{ p: 3 }}>
            <Alert severity="info" sx={{ mb: 3 }}>
              <strong>🎉 New TypeScript Version!</strong> This is the modern,
              cross-platform version built with Electron + React + Material-UI.
            </Alert>

            <Typography variant="h6" gutterBottom>
              🔧 What's New:
            </Typography>
            <List>
              <ListItem>
                <ListItemIcon>
                  <CheckCircle color="primary" />
                </ListItemIcon>
                <ListItemText primary="Cross-platform GUI (Windows, Mac, Linux)" />
              </ListItem>
              <ListItem>
                <ListItemIcon>
                  <CheckCircle color="primary" />
                </ListItemIcon>
                <ListItemText primary="TypeScript for better safety and development" />
              </ListItem>
              <ListItem>
                <ListItemIcon>
                  <CheckCircle color="primary" />
                </ListItemIcon>
                <ListItemText primary="Modern React + Material-UI Design" />
              </ListItem>
              <ListItem>
                <ListItemIcon>
                  <CheckCircle color="primary" />
                </ListItemIcon>
                <ListItemText primary="Enhanced memory visualization" />
              </ListItem>
              <ListItem>
                <ListItemIcon>
                  <CheckCircle color="primary" />
                </ListItemIcon>
                <ListItemText primary="Real-time CAN monitoring" />
              </ListItem>
            </List>

            <Alert severity="warning" sx={{ mt: 3 }}>
              <Warning sx={{ mr: 1 }} />
              <strong>Safety First!</strong> This tool can permanently damage
              actuators if used incorrectly. Always backup memory dumps and
              understand the analysis before making changes.
            </Alert>
          </Paper>
        </Grid>

        <Grid item xs={12} md={6}>
          <Paper sx={{ p: 3 }}>
            <Typography variant="h6" gutterBottom>
              Quick Start
            </Typography>
            <Stepper orientation="vertical" activeStep={0}>
              {steps.map((label) => (
                <Step key={label}>
                  <StepLabel>{label}</StepLabel>
                </Step>
              ))}
            </Stepper>
          </Paper>
        </Grid>

        <Grid item xs={12} md={6}>
          <Paper sx={{ p: 3 }}>
            <Typography variant="h6" gutterBottom>
              Legacy Python Version
            </Typography>
            <Typography variant="body1" paragraph>
              The original Python CLI tools are available in the{" "}
              <code>legacy-python/</code> folder.
            </Typography>
            <Button variant="outlined" startIcon={<Folder />}>
              View Legacy Tools
            </Button>
          </Paper>
        </Grid>
      </Grid>
    </Box>
  );
}

export default Dashboard;
